server:
  port: 8761 # 1?

spring:
  application:
    name: discovery-service # 2?

eureka:
#  server:
#    renewal-percent-threshold: 0.33
#  instance:
#    lease-renewal-interval-in-seconds: 30
  client:
    register-with-eureka: false # 3?
    fetch-registry: false  # 4?